### PR TITLE
docs: improve verifier documentation

### PR DESCRIPTION
**Pull request by August-Brandt**
Updates verifier documentation with more information, and matches the format of other documentaion

### CODE REVIEW

**Comment by Slug-Boi** [comment]
Can we please concatenate this into one branch with all the updates. I don't see the reason for doing 12+ branches just to update the documentation.

**Review by Slug-Boi — CHANGES_REQUESTED** [review]
Please see my comment

**Comment by August-Brandt** [comment]
Sure. Is there already a branch set up for this or should I make one?

**Comment by Slug-Boi** [comment]
We do not have a branch so feel free to make one and I'll merge my branch into it that i worked on Tuesday

**Pull request closed without merging**
