### PR TITLE
feat: integrate cobra with the --fetch flag/command 

### PR DESCRIPTION
**Pull request by Alex-itu**
This integrates the fetch command for fetching whitelisted files from any git repo.
To use this say 'go run main.go fetch <Whitelist_Filepath> [Url1] [Branch1] [Whitelist_Filepath1]'.
For clarification, the '[' indicates fetching optional extra repos. The '<' are for must-haves.
Resolves. [57](https://github.com/NovoNordisk-OpenSource/decentralized-tech-radar/issues/57)

### CODE REVIEW

**Comment by Slug-Boi** [comment]
May I suggest we comment out the end to end tests on this branch and if the tests still complain then merge main into this branch so we get green checkmark?

**Review by August-Brandt — APPROVED** [review]
Looks good

**Comment by Haruyzal** [comment]
> May I suggest we comment out the end to end tests on this branch and if the tests still complain then merge main into this branch so we get green checkmark?
> 
> Of course this branch should then be merged before Merger

@Slug-Boi is it still of importance to merge the Merger branch into main first?

**Comment by Slug-Boi** [comment]
> > May I suggest we comment out the end to end tests on this branch and if the tests still complain then merge main into this branch so we get green checkmark?
> > Of course this branch should then be merged before Merger
> 
> @Slug-Boi is it still of importance to merge the Merger branch into main first?

Since that branch has the E2E test commented out this would not need to be the case no

**Review by Haruyzal — COMMENTED** [review]
Looks great! I've got some clarifying questions though :pray:

**Pull request merged**
