### PR TITLE
Feat: Write to html

### PR DESCRIPTION
**Pull request by JonasSkjodt**
This is an update on the code written in a smaller team, where the program can create an index.html and write a CLI command to it. This is issue ([#19](https://github.com/NovoNordisk-OpenSource/decentralized-tech-radar/issues/19))

**Please dont merge**, as we'd like both lasse and casper to view the smaller chunk of code from the given branch after each of you agree to the code.

### CODE REVIEW

**Review by Slug-Boi — APPROVED** [review]
Looks good. Seems fairly simple to understand and looks like we could very easily change styling later. Good job!

**Comment by Haruyzal** [comment]
Looks like a good start!

**Review by Haruyzal — APPROVED** [review]
Looks like a good start! Think I'll understand it better when the code gets more fleshed out later :')

**Review by zqueamish — APPROVED** [review]

**Comment by August-Brandt** [comment]
These changes have been moved into another PR

**Pull request closed without merging**
